name: Upload DAGs to GCS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT }} 
        service_account_key: ${{ secrets.GCP_KEY }}

    - name: Deploy to Composer
      run: |
        gcloud composer environments storage dags import \
          --environment ${{ secrets.GCP_COMPOSER_ENVIRONMENT }} \
          --location ${{ secrets.GCP_REGION }} \
          --source airflow/dags/
